### ISSUE TITLE
Package renaming

### ISSUE THREAD

**Issue by encody** [NEARFoundation/near-sdk-contract-tools#85]
This issue is resolved when all of the below point are resolved or moot:
* Should the name of the package be changed?
* To what should the name of the package be changed?
* All internal references/mentions have been updated, the repository has been moved, the old package has been deprecated on crates.io, and the renamed package has been published to crates.io.

**Comment by twitu** [comment]
I believe `near-contract-tools` is the right name for this crate and it doesn't need to change. This crate provides helper functions and macros, essentially tools to enhance the functionality of a contract. In that sense the name is fitting.

That being said if I were propose a name change it would be one of the following

| name | comment |
| -- | -- |
| near-contract-patterns | Better option. Indicates exactly how what it offers to someone building a near contract. But may not fit, in case the scope of this crate grows to include more than patterns |
| near-contract-helpers | Good option. But indicates that it helps writing contracts by abstracting complex syntax and does not necessarily add new functionality |
| near-contract-macros/near-contract-derive | Ok option. Generic name that describes what the crate contains but not how it helps the user. It's probably more suited when the expected user is building rust applications or libraries |

`helpers`, `derive`, `macros` suffix are commonly used in the rust ecosystem but they tend to indicate general purpose use. This crate is specific to tools for near contracts so it doesn't need to follow this convention.

Secondly I think user generally find helper/complimentary crates through the documentation/readme/blogs. Having this crate linked prominently in a few places will ensure users can find it irrespective of name.

**Comment by encody** [comment]
After some internal consultation, we've decided that the name change that will cause the least confusion and is still the most true to the package is `near-sdk-contract-tools`.
